workspace:
  base: /data/redis
  path: .
pipeline:
  init:
    image: 'node:latest'
    commands:
      - 'echo "begin"'
    when:
      event: [push, tag, deployment]
      branch: [master, develop]
  build:
    image: 'node:latest'
    environment:
      - TZ=Asia/Shanghai
    commands:
      - 'cd /data/redis/redis/ && make'
    when:
      event: [push, tag, deployment]
      branch: [master, develop]